"""Phase 3.1 — Narrative Director: Gemini Native Interleaved Output.

This is the AI Historian project's primary implementation of Gemini's native
interleaved output capability (response_modalities=["TEXT","IMAGE"]).

A single Gemini call per documentary scene produces BOTH:
  - A scene concept note (text: creative direction, composition intent)
  - A storyboard illustration (image: inline base64, generated by Gemini)

This is architecturally distinct from separate Imagen 3 calls in Phase V:
here Gemini itself acts as the creative director, generating visuals and
narration direction in one unified reasoning pass. Phase V's Imagen 3 then
uses these storyboard frames as cinematic reference for the final frames.

Two interleaved output moments in the full pipeline
---------------------------------------------------
1. This agent (Phase 3.1): response_modalities=["TEXT","IMAGE"] —
   Gemini generates scene storyboards inline with narration direction.
2. live-relay (always-on): Gemini Live API with gemini-2.5-flash-native-audio
   generates audio and text simultaneously in a single bidirectional stream.

Session state contract
----------------------
Inputs (must be present before Phase 3.1 runs):
    session.state["script"]        -- list[dict] SegmentScript dicts (Phase III)
    session.state["visual_bible"]  -- Imagen 3 style guide string (Phase I)
    session.state["scene_briefs"]  -- list[dict] SceneBrief dicts (Phase I)

Outputs (written by this agent):
    session.state["storyboard_images"]  -- dict[scene_id, list[str]] GCS URIs
                                           One URI per scene (primary storyboard frame)
"""

from __future__ import annotations

import asyncio
import base64
import logging
from datetime import timedelta
import os
import time
import uuid
from collections.abc import AsyncGenerator
from typing import Any

from google import genai as google_genai
from google.adk.agents.base_agent import BaseAgent
from google.adk.agents.invocation_context import InvocationContext
from google.cloud import storage
from google.genai import types as genai_types
from pydantic import ConfigDict, Field

from .sse_helpers import (
    SSEEmitter,
    build_agent_status_event,
    build_pipeline_phase_event,
    build_segment_update_event,
    build_storyboard_image_ready_event,
    build_storyboard_scene_start_event,
    build_storyboard_text_chunk_event,
    build_stats_update_event,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Model configuration
# ---------------------------------------------------------------------------
# gemini-2.0-flash-exp supports response_modalities=["TEXT","IMAGE"] on
# Vertex AI. Override via NARRATIVE_DIRECTOR_MODEL env var if Google releases
# a stable interleaved-output model before the submission deadline.
_DEFAULT_INTERLEAVED_MODEL = "gemini-2.5-flash-image"


# ---------------------------------------------------------------------------
# Prompt template
# ---------------------------------------------------------------------------
_STORYBOARD_PROMPT = """\
You are the creative director of a cinematic historical documentary called "AI Historian".
Your task is to generate a storyboard illustration for one documentary scene.

VISUAL BIBLE (style reference for all imagery):
{visual_bible}

SCENE INFORMATION:
Title: {title}
Mood: {mood}
Narrative role: {narrative_role}

NARRATION (the voiceover for this scene):
{narration_script}

RESEARCH CONTEXT:
{research_context}

YOUR TASK:
First, write a brief creative direction note (2–3 sentences) describing the
key visual composition you are about to illustrate — what the viewer should
see, feel, and remember from this moment.

Then generate ONE storyboard illustration that captures the most powerful
visual moment from this scene. The illustration must:
- Match the Visual Bible style exactly (era, palette, composition rules)
- Convey the mood: {mood}
- Work as a documentary cinematography reference frame
- Be cinematic 16:9 composition
- Contain NO anachronisms, NO modern elements
- Depict the historical period accurately

Generate the illustration now.
"""


# ---------------------------------------------------------------------------
# NarrativeDirectorAgent
# ---------------------------------------------------------------------------


class NarrativeDirectorAgent(BaseAgent):
    """Phase 3.1: generates Gemini-native storyboard frames via interleaved output.

    For each documentary segment, makes one Gemini call with
    ``response_modalities=["TEXT", "IMAGE"]``. Gemini returns a creative
    direction note (text) and a storyboard illustration (inline image) in
    a single interleaved response.

    The inline image bytes are uploaded to GCS. The GCS URI is stored in
    ``session.state["storyboard_images"][scene_id]`` for Phase V to use as
    a cinematographic reference when calling Imagen 3.

    Graceful degradation: if Gemini returns no image for a scene (safety
    filter, quota, model limitation), that scene is skipped silently and
    Phase V falls back to its existing Imagen 3 logic unchanged.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    emitter: Any = Field(default=None)
    gcs_bucket: str = Field(default="")
    gcp_project: str = Field(default="")
    model: str = Field(default=_DEFAULT_INTERLEAVED_MODEL)

    async def _run_async_impl(
        self,
        ctx: InvocationContext,
    ) -> AsyncGenerator[Any, None]:
        """Execute Phase 3.1: interleaved TEXT+IMAGE storyboard generation."""

        session_id: str = ctx.session.id
        t_start = time.monotonic()

        # ── Emit pipeline phase marker ────────────────────────────────────────
        if self.emitter:
            await self.emitter.emit(
                "pipeline_phase",
                build_pipeline_phase_event(
                    phase=3.1,
                    label="CREATIVE DIRECTION",
                    message=(
                        "Gemini is generating storyboard illustrations for each scene "
                        "— text and imagery produced together in a single interleaved call."
                    ),
                ),
            )

        # ── Read session state ────────────────────────────────────────────────
        script_raw: list[dict[str, Any]] = ctx.session.state.get("script", [])
        visual_bible: str = ctx.session.state.get("visual_bible", "")
        scene_briefs_raw: list[dict[str, Any]] = ctx.session.state.get("scene_briefs", [])

        if not script_raw:
            logger.warning(
                "[NarrativeDirector] No script found in session state for %s — "
                "skipping storyboard generation.",
                session_id,
            )
            return
            yield  # make this an AsyncGenerator

        # Build scene_id → brief lookup for research context
        brief_by_scene: dict[str, dict[str, Any]] = {
            b.get("scene_id", ""): b for b in scene_briefs_raw
        }

        # ── Initialise Gemini client ──────────────────────────────────────────
        client = google_genai.Client(
            vertexai=True,
            project=self.gcp_project,
            location="global",  # gemini-2.5-flash-image requires global region
        )

        # ── Initialise GCS client ─────────────────────────────────────────────
        gcs_client = storage.Client(project=self.gcp_project)
        bucket = gcs_client.bucket(self.gcs_bucket)

        # ── Per-scene storyboard generation ──────────────────────────────────
        storyboard_map: dict[str, list[str]] = {}
        frames_generated = 0

        for i, seg_dict in enumerate(script_raw):
            scene_id   = seg_dict.get("scene_id", f"scene_{i}")
            segment_id = seg_dict.get("id", f"segment_{i}")
            title      = seg_dict.get("title", "Untitled Scene")
            mood       = seg_dict.get("mood", "cinematic")
            role       = seg_dict.get("narrative_role", "")
            narration  = seg_dict.get("narration_script", "")

            brief = brief_by_scene.get(scene_id, {})
            research_context = brief.get("summary", brief.get("key_themes", ""))

            # Emit agent status: queued
            if self.emitter:
                await self.emitter.emit(
                    "agent_status",
                    build_agent_status_event(
                        agent_id=f"narrative_director_{i}",
                        status="queued",
                        query=f"Storyboard: {title}",
                    ),
                )

            # ── Emit storyboard_scene_start ────────────────────────────────
            if self.emitter:
                await self.emitter.emit(
                    "storyboard_scene_start",
                    build_storyboard_scene_start_event(
                        scene_id=scene_id,
                        segment_id=segment_id,
                        title=title,
                        mood=mood,
                    ),
                )

            prompt = _STORYBOARD_PROMPT.format(
                visual_bible=visual_bible[:2000],  # trim to avoid token overflow
                title=title,
                mood=mood,
                narrative_role=role,
                narration_script=narration[:1500],
                research_context=str(research_context)[:800],
            )

            # Augment with shared style terms for visual coherence
            try:
                from .prompt_style_helpers import build_style_block

                style_terms = build_style_block(
                    visual_bible=visual_bible,
                    era=brief.get("era", ""),
                    mood=mood,
                    title=title,
                    narrative_role=role,
                    scene_brief=brief,
                )
                prompt += (
                    f"\n\n{style_terms}"
                    "\n\nMatch these style terms exactly in the illustration."
                )
            except ImportError:
                pass  # Style helpers not available — proceed with base prompt

            # Emit agent status: searching (= generating)
            if self.emitter:
                await self.emitter.emit(
                    "agent_status",
                    build_agent_status_event(
                        agent_id=f"narrative_director_{i}",
                        status="searching",
                        query=f"Generating interleaved text+image for: {title}",
                    ),
                )

            try:
                # ── THE CORE INTERLEAVED CALL ─────────────────────────────────
                # One Gemini call → TEXT creative direction + IMAGE storyboard frame
                # This is the native interleaved output capability.
                response = await client.aio.models.generate_content(
                    model=self.model,
                    contents=[prompt],
                    config=genai_types.GenerateContentConfig(
                        response_modalities=["TEXT", "IMAGE"],
                        temperature=0.7,
                    ),
                )

                # ── Parse interleaved response ────────────────────────────────
                # Process parts sequentially: text parts emit storyboard_text_chunk,
                # image parts get uploaded to GCS with signed URLs and emit
                # storyboard_image_ready. This preserves Gemini's interleaved ordering.
                image_uris: list[str] = []
                signed_urls: list[str] = []
                direction_text: str = ""

                if response.candidates:
                    for part in response.candidates[0].content.parts:
                        if hasattr(part, "text") and part.text:
                            direction_text += part.text

                            # Emit text chunk immediately for streaming UX
                            if self.emitter:
                                await self.emitter.emit(
                                    "storyboard_text_chunk",
                                    build_storyboard_text_chunk_event(
                                        scene_id=scene_id,
                                        text=part.text,
                                    ),
                                )

                        elif hasattr(part, "inline_data") and part.inline_data:
                            # Got an inline image from Gemini — upload to GCS
                            image_bytes = part.inline_data.data
                            mime_type   = part.inline_data.mime_type or "image/jpeg"
                            ext         = "jpg" if "jpeg" in mime_type else "png"

                            gcs_path = (
                                f"sessions/{session_id}/storyboards/"
                                f"{scene_id}_frame_{len(image_uris)}_{uuid.uuid4().hex[:8]}.{ext}"
                            )

                            blob = bucket.blob(gcs_path)

                            # Upload synchronously via executor (GCS client is sync)
                            loop = asyncio.get_event_loop()
                            await loop.run_in_executor(
                                None,
                                lambda b=image_bytes, bl=blob, m=mime_type: bl
                                    .upload_from_string(data=b, content_type=m),
                            )

                            gcs_uri = f"gs://{self.gcs_bucket}/{gcs_path}"
                            image_uris.append(gcs_uri)

                            # Generate 4-hour signed HTTPS URL for frontend rendering
                            signed_url: str = await loop.run_in_executor(
                                None,
                                lambda bl=blob: bl.generate_signed_url(
                                    expiration=timedelta(hours=4),
                                    method="GET",
                                    version="v4",
                                ),
                            )
                            signed_urls.append(signed_url)
                            frames_generated += 1

                            logger.info(
                                "[NarrativeDirector] Storyboard frame uploaded: %s",
                                gcs_uri,
                            )

                            # Emit storyboard_image_ready with signed URL
                            if self.emitter:
                                caption = (
                                    direction_text[:200].strip()
                                    if direction_text
                                    else f"Storyboard frame for: {title}"
                                )
                                await self.emitter.emit(
                                    "storyboard_image_ready",
                                    build_storyboard_image_ready_event(
                                        scene_id=scene_id,
                                        segment_id=segment_id,
                                        image_url=signed_url,
                                        caption=caption,
                                    ),
                                )

                if image_uris:
                    storyboard_map[scene_id] = image_uris

                    # Emit segment_update with storyboard images (GCS URIs for Phase V)
                    if self.emitter:
                        await self.emitter.emit(
                            "segment_update",
                            build_segment_update_event(
                                segment_id=segment_id,
                                scene_id=scene_id,
                                status="storyboard_ready",
                                title=title,
                                mood=mood,
                                image_urls=image_uris,
                            ),
                        )

                    logger.info(
                        "[NarrativeDirector] Scene %s: %d storyboard frame(s). "
                        "Direction: %.80s…",
                        scene_id,
                        len(image_uris),
                        direction_text,
                    )
                else:
                    # Gemini returned text only — no image generated (safety / model limit)
                    logger.warning(
                        "[NarrativeDirector] Scene %s: no inline image returned by Gemini. "
                        "Phase V will use Imagen 3 directly.",
                        scene_id,
                    )

                # Emit agent status: done
                if self.emitter:
                    await self.emitter.emit(
                        "agent_status",
                        build_agent_status_event(
                            agent_id=f"narrative_director_{i}",
                            status="done",
                            query=f"Storyboard: {title}",
                            elapsed=0.0,
                            facts=[
                                f"Gemini interleaved call: text + {len(image_uris)} image(s)",
                                direction_text[:120].strip() if direction_text else "No direction note",
                            ],
                        ),
                    )

            except Exception as exc:
                logger.exception(
                    "[NarrativeDirector] Scene %s interleaved generation failed: %s",
                    scene_id,
                    exc,
                )
                if self.emitter:
                    await self.emitter.emit(
                        "agent_status",
                        build_agent_status_event(
                            agent_id=f"narrative_director_{i}",
                            status="error",
                            query=f"Storyboard: {title}",
                        ),
                    )
                # Non-fatal: continue to next scene

        # ── Write storyboard map to session state ─────────────────────────────
        ctx.session.state["storyboard_images"] = storyboard_map

        # ── Emit stats update ─────────────────────────────────────────────────
        if self.emitter and frames_generated > 0:
            await self.emitter.emit(
                "stats_update",
                build_stats_update_event(
                    sources_found=None,
                    facts_verified=frames_generated,
                    segments_ready=None,
                ),
            )

        elapsed = time.monotonic() - t_start
        logger.info(
            "[NarrativeDirector] Phase 3.1 complete for session %s: "
            "%d storyboard frames across %d scenes in %.1fs.",
            session_id,
            frames_generated,
            len(storyboard_map),
            elapsed,
        )
        return
        yield  # AsyncGenerator protocol


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------


def build_narrative_director_agent(
    emitter: SSEEmitter | None = None,
) -> NarrativeDirectorAgent:
    """Construct a NarrativeDirectorAgent from environment variables.

    Environment variables:
        GCP_PROJECT_ID            -- GCP project for Vertex AI + GCS
        GCS_BUCKET_NAME           -- GCS bucket for storyboard uploads
        NARRATIVE_DIRECTOR_MODEL  -- Gemini model with interleaved output support
                                     (default: gemini-2.0-flash-exp)
    """
    return NarrativeDirectorAgent(
        name="narrative_director",
        description=(
            "Phase 3.1: Gemini native interleaved output agent. "
            "Generates documentary storyboard frames (TEXT+IMAGE) in a single "
            "Gemini call using response_modalities=['TEXT','IMAGE']. "
            "Storyboards are uploaded to GCS and used as reference by Phase V Imagen 3."
        ),
        emitter=emitter,
        gcs_bucket=os.environ.get("GCS_BUCKET_NAME", ""),
        gcp_project=os.environ.get("GCP_PROJECT_ID", ""),
        model=os.environ.get("NARRATIVE_DIRECTOR_MODEL", _DEFAULT_INTERLEAVED_MODEL),
    )
