"""Pydantic types for the Visual Interleave Agent (Phase 3.3).

The Visual Interleave Agent reads beat data from Phase 3.2 and assigns each
beat a ``visual_type`` that determines which generation path Phase V uses:

- ``illustration`` — Gemini interleaved TEXT+IMAGE (already generated by Phase 3.2)
- ``cinematic`` — Imagen 3 photorealistic frame (Phase V generates per-beat)
- ``video`` — Veo 2 short clip (Phase V generates per-beat)
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class BeatVisualAssignment(BaseModel):
    """Assignment of a visual type to a single narration beat."""

    beat_index: int = Field(description="Zero-based beat index within the segment")
    visual_type: Literal["illustration", "cinematic", "video"] = Field(
        description=(
            "Which visual generation path to use: "
            "'illustration' (keep Phase 3.2 Gemini image), "
            "'cinematic' (generate Imagen 3 frame), "
            "'video' (generate Veo 2 clip)"
        )
    )
    generation_prompt: str | None = Field(
        default=None,
        description=(
            "Tailored prompt for Imagen 3 or Veo 2 generation. "
            "Null for 'illustration' type (Phase 3.2 already generated)."
        ),
    )


class SegmentVisualPlan(BaseModel):
    """Visual type assignments for all beats in a single segment."""

    segment_id: str
    assignments: list[BeatVisualAssignment]
